Feature/enable jdbc options
exasol/spark-exasol-connector pull request #77
Opened 2020-09-23 13:26 UTC by 3cham

This fixes #76

2020-09-23 13:42 UTC, morazow requested changes
Hey @3cham,

Thanks for the pull request!

I have minor change requests to the exception messages, then all looks good.

2020-09-23 13:42 UTC, morazow commented on src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala
> +        "jdbc option should not start or end with semicolon"
```suggestion
        "Jdbc options should not start or end with semicolon."
```

2020-09-23 13:42 UTC, morazow commented on src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala
> +              s"property invalid: $kv does not have key=value format"
```suggestion
              s"Invalid property: $kv does not have key=value format."
```

2020-09-23 13:54 UTC, 3cham commented
@morazow : that was fast 👍 yeah I fixed the exception messages. Hope you're still doing well 

Take care

2020-09-24 07:40 UTC, morazow approved these changes

2020-09-24 07:41 UTC, morazow commented
Hey @3cham,

Great to hear from you!

Thanks again sending the patch! We can release quick new version soon.

Best

2020-09-24 07:43 UTC, merged